import "./globals.css";

export const metadata = {
  title: "WEB Tutorial",
  description: "Generated by Wonjang",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div>
          <h1>
            <a href="/">WelCome</a>
          </h1>
          <ol>
            <li>
              <a href="/read/1">HTML</a>
            </li>
            <li>
              <a href="/read/2">CSS</a>
            </li>
            <li>
              <a href="/read/3">JavaScript</a>
            </li>
          </ol>
        </div>
        {children}
        <ul>
          <li>
            <a href="create">Create</a>
          </li>
          <li>
            <a href="update/1">Update</a>
          </li>
          <li>
            <input type="button" value="Delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
